### PR TITLE
Checkbox file selection.

### PR DESCRIPTION
**Pull request by jovaska1337**
Allow external files to be enabled/disabled via a checkbox. Disabled files are saved in the config file under zdl.save/disabled.
This basically implements what was discussed in issue #67.

### CODE REVIEW

**Comment by jovaska1337** [comment]
Apparently my other commit was also added into this pull request (I'm new to using git). It just changes the DOS newlines into UNIX newlines in two files.

**Comment by duganchen** [comment]
Your work looks good, but even with your latest update, the changeset is much larger than it should be. Could you please fix that? I think the problem might be that your git isn't set up to commit Unix-style.

Please fix that, and update the pull request with a --force-push.

**Comment by jovaska1337** [comment]
> Your work looks good, but even with your latest update, the changeset is much larger than it should be. Could you please fix that? I think the problem might be that your git isn't set up to commit Unix-style.
> 
> Please fix that, and update the pull request with a --force-push.

That didn't seem to change anything. The newline changing commit is making it large since it overwrites ZDLMainWindow.cpp and ZDLSettingsTab.h with their old contents minus the carriage returns.

**Comment by jovaska1337** [comment]
> That didn't seem to change anything. The newline changing commit is making it large since it overwrites ZDLMainWindow.cpp and ZDLSettingsTab.h with their old contents minus the carriage returns.

To make this more clear (which I probably should've done from the start):
ZDLMainWindow.cpp and ZDLSettingsTab.h have CRLF line endings as they currently are (unlike every other file) and my commit removes the carriage returns.

**Review by duganchen — APPROVED** [review]

**Comment by duganchen** [comment]
Aah, I see. There's no problem then. Thanks for this!

**Pull request merged**
